org.apache.derby.impl.store.access.BackingStoreHashTableFromScan does not honor ResultSet holdability    After an unrelated statement on the same connection commits  and after some number of successful calls to ResultSet.next()  a subsequent call to ResultSet.next() throws an SQLException with a message like: The heap container with container id Container(-1  1173965368428) is closed. This seems to be related to the hard-coded passing of false to the super in the constructor of org.apache.derby.impl.store.access.BackingStoreHashTableFromScan.Steps to reproduce:1. Execute a statement on a connection that returns a result set.2. Execute a second statement on the same connection that modifies the database and commits.3. Call next() on the first result set until the exception is thrown.Note that the number of rows that can be successfully retrieved from the result set seems to be related to the amount of data per row. Increasing the number of columns in the result set or the length of the columns causes the exception to be taken sooner.The attached test program demonstrates the issue.   