Client does not return SQLException on XAConnection.getXAResource() on a closed connection  Embedded does    In the following scenario from converted test DataSourceTest:(non-tested code based on the test code)---------------- ClientXADataSource dsx = new ClientXADataSource(); dsx.setDatabaseName('tstdb'); XAConnection xac = dsx.getXAConnection(); XAConnection xac2 = dsx.getXAConnection(); XAResource xar2 = xac2.getXAResource(); xac2.close(); // allow close on already closed XAConnection xac2.close(); try { xac2.getXAResource(); // Network Server does not think this is worth an exception. } catch (SQLException sqle) { System.out.println('expect a 08003 as with Embedded'); }------------------With DerbyNetClient  the xac2.getXAResource() does not return an SQLException.This ought to be documented if expected  or fixed.   