failure in jdbcapi.StatementJdbc20Test:testCompletionClosure_jdbc4_1 with j9 (j2ME/CDC)    After revision 1061824 for DERBY-4869  there is the following failure in the tests when run with ibm's j9:1) testCompletionClosure_jdbc4_1(org.apache.derbyTesting.functionTests.tests.jdbcapi.StatementJdbc20Test)java.sql.SQLException: The exception 'java.lang.NoClassDefFoundError: java.sql.DriverManager' was thrown while evaluating an expression. at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source) at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source) at org.apache.derby.impl.jdbc.Util.seeNextException(Unknown Source) at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source) at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source) at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source) at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source) at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source) at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source) at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source) at org.apache.derbyTesting.functionTests.tests.jdbcapi.StatementJdbc20Test.vetClosedCall(StatementJdbc20Test.java:357) at org.apache.derbyTesting.functionTests.tests.jdbcapi.StatementJdbc20Test.vetClosure(StatementJdbc20Test.java:317) at org.apache.derbyTesting.functionTests.tests.jdbcapi.StatementJdbc20Test.testCompletionClosure_jdbc4_1(StatementJdbc20Test.java:309) at java.lang.reflect.AccessibleObject.invokeV(AccessibleObject.java:195) at org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:112) at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22) at junit.extensions.TestSetup$1.protect(TestSetup.java:19) at junit.extensions.TestSetup.run(TestSetup.java:23) at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)Caused by: java.sql.SQLException: Java exception: 'java.sql.DriverManager: java.lang.NoClassDefFoundError'. at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source) at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source) at org.apache.derby.impl.jdbc.Util.javaException(Unknown Source) at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source) ... 33 moreCaused by: java.lang.NoClassDefFoundError: java.sql.DriverManager at org.apache.derbyTesting.functionTests.tests.jdbcapi.StatementJdbc20Test.dynamicResults(StatementJdbc20Test.java:449) at org.apache.derby.exe.acdf1940dax012dxb95exf375xffffd1bbe3d70.g0(Unknown Source) at java.lang.reflect.AccessibleObject.invokeV(AccessibleObject.java:195) at org.apache.derby.impl.services.reflect.ReflectMethod.invoke(Unknown Source) at org.apache.derby.impl.sql.execute.CallStatementResultSet.open(Unknown Source) at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source) at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source) ... 29 moreNote  that there is no record of how this test would fare with the phoneME - those tests haven't been running since mid-September 2010 (http://dbtg.foundry.sun.com/derby/test/Daily/javaME/testing/Full/index_all.html).   