Lacking cleanup in CheckConstraintTest.testJira4282()    The test case testJira4282 in CheckConstraintTest doesn't drop the table it creates. The table itself has a unique name that doesn't conflict with any other test case  but it also has a constraint with a generic name (CK1) that is in conflict with constraints created in testCheckConstraints and testPositionalUpdate. If testJira4282 runs before any of those test cases  the test will fail.Example from the nightly tests:http://dbtg.foundry.sun.com/derby/test/Daily/jvm1.7/testing/testlog/lin/1076682-suitesAll_diff.txt1) testCheckConstraints(org.apache.derbyTesting.functionTests.tests.lang.CheckConstraintTest)java.sql.SQLException: Constraint 'CK1' already exists in Schema 'APP'. at org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source) at org.apache.derby.client.am.SqlException.getSQLException(Unknown Source) at org.apache.derby.client.am.Statement.executeUpdate(Unknown Source) at org.apache.derbyTesting.functionTests.tests.lang.CheckConstraintTest.testCheckConstraints(CheckConstraintTest.java:243)   