Sequence generator makes CREATE TRIGGER fail with internal error    I'm seeing this on trunk:ij version 10.11ij&gt; connect 'jdbc:derby:memory:db;create=true';ij&gt; create table t1(x int  y int  z int);0 rows inserted/updated/deletedij&gt; create table t2(x int  y int  z int);0 rows inserted/updated/deletedij&gt; create sequence seq;0 rows inserted/updated/deletedij&gt; values next value for seq;1 ------------21474836481 row selectedij&gt; create trigger tr1 after insert on t1 insert into t2(x) values (next value for seq);ERROR 40XT8: An internal error was identified by RawStore module. Internal state detail from the transaction is as follows: savedEndStatus = 0needSync = falsejustCreated = falsemyGlobalId = nullmyId = nullstate = 0inComplete = nullseenUpdates = falseinPostCommitProcessing = falselogStart = nulllogLast = nullrecoveryTransaction = falsepostCompleteMode = falsesanityCheck_xaclosed = falsetransName = UserTransactionreadOnly = falseflush_log_on_xact_end = truebackupBlocked = falsedontWaitForLocks = false   