In doTry .. doCatch .. doFinally the FAILURE_ENDPOINT details should be available as well in case an exception was thrown    In doCatch you have access to the caught exception using the exchange property CAUGHT_EXCEPTION. But we should also make FAILURE_ENDPOINT available as well. This information is present when you use onException / errorHandler. So we should make this consistent  and be avail in doCatch / doFinally as well.   