<title>Issue 8576 -   chromium -    Buildbots recovering from a failed svn operation (trying again) isn't working anymore - Project Hosting on Google Code</title> <pre> Recovering from a failed svn operation isn't working anymore.  doVCFull   complains that it can't make the build dir.  It's not clear why it isn't   being moved to build.dead properly on failure. Maybe crash-services is   still open?    Old example:    ________ running 'svn checkout http://google-  url.googlecode.com/svn/trunk@47 googleurl' in 'C:bslavewebkit-release-  builderbuild'  Error: failed to run command: svn checkout http://google-  url.googlecode.com/svn/trunk@47 googleurl  svn: No results returned from filesystem read operation.  update failed  trying 4 more times after 300 seconds    remoteFailed: [Failure instance: Traceback from remote host -- Traceback   (most recent call last):   File &quot;C:bpylibstwistedinternetposixbase.py&quot;  line 226  in mainLoop     self.runUntilCurrent()   File &quot;C:bpylibstwistedinternetbase.py&quot;  line 555  in runUntilCurrent     call.func(*call.args  **call.kw)   File &quot;C:bpylibstwistedinternetdefer.py&quot;  line 229  in callback     self._startRunCallbacks(result)   File &quot;C:bpylibstwistedinternetdefer.py&quot;  line 294  in   _startRunCallbacks     self._runCallbacks()  --- &lt;exception caught here&gt; ---   File &quot;C:bpylibstwistedinternetdefer.py&quot;  line 307  in _runCallbacks     self.result = callback(self.result  *args  **kw)   File &quot;C:bpylibsbuildbotslavecommands.py&quot;  line 1329  in &lt;lambda&gt;     d.addCallback(lambda res: self.doVCFull())   File &quot;C:bscriptscommongoogle_commands.py&quot;  line 203  in doVCFull     os.mkdir(dir)  exceptions.OSError: [Errno 17] File exists: 'C:/b/slavewebkit-release-  builderbuild'  ] </pre>